name: CI

on:
  project_card:
    types: [moved]

jobs:
  labels-from-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install

    - name: unlabel issues from 'To do'
      uses: ./.
      if: |
        github.event_name == 'project_card' &&
        (
          github.event.project_card.column_id == 9423433
        )
      with:
        repo-token: ${{secrets.GH_ACCESS_TOKEN}}
        remove-labels: "Status: Bloqueado, Status: Em Progresso"

    - name: label issues from 'In progress'
      uses: ./.
      if: |
        github.event_name == 'project_card' &&
        (
          github.event.project_card.column_id == 9423434
        )
      with:
        repo-token: ${{secrets.GH_ACCESS_TOKEN}}
        add-labels: "Status: Em Progresso"
        remove-labels: "Status: Bloqueado"

    - name: label issues from 'Blocked'
      uses: ./.
      if: |
        github.event_name == 'project_card' &&
        (
          github.event.project_card.column_id == 9423437
        )
      with:
        repo-token: ${{secrets.GH_ACCESS_TOKEN}}
        add-labels: "Status: Bloqueado"
        remove-labels: "Status: Em Progresso"